import 'jquery-validation';

export const getStatus = {
	en: {
		created: 'Created',
		accepted: 'Accepted',
		out_of_stock: 'Out of stock',
		warning: 'Warning',
		wrong_credentials: 'Wrong credentials',
		wrong_backup: 'Wrong backup',
		no_enough_stock: 'Not enough stock',
		not_enough_stock: 'Not enough stock',
		no_enough_coins_to_start: 'Not enough coins to start',
		not_enough_coins_to_start: 'Not enough coins to start',
		waiting_payment: 'Waiting payment',
		payment_failed: 'Payment failed',
		error_payment: 'Payment failed',
		no_access_to_fifa_21_webapp: 'No access to FIFA 21 Web-App',
		error_fut: 'FUT error',
		fut_error: 'FUT error',
		customer_online: 'FIFA account currently in use',
		success: 'Success',
		finished: 'Finished',
		payed: 'Paid',
		progress: 'In progress',
	},
	ru: {
		created: 'Создан',
		accepted: 'Принят',
		out_of_stock: 'Распродано',
		warning: 'Предупреждение',
		wrong_credentials: 'Неверные учётные данные',
		wrong_backup: 'Неверные резервные коды',
		no_enough_stock: 'Не хватает монет, нет в наличии',
		not_enough_stock: 'Не хватает монет, нет в наличии',
		no_enough_coins_to_start: 'Не достаточно монет, для начала',
		not_enough_coins_to_start: 'Не достаточно монет, для начала',
		waiting_payment: 'Ожидает оплаты',
		payment_failed: 'Платеж не прошел',
		error_payment: 'Платеж не прошел',
		no_access_to_fifa_21_webapp: 'Нет доступа к FIFA 21 Web-App',
		error_fut: 'Ошибка FUT',
		fut_error: 'Ошибка FUT',
		customer_online: 'Аккаунт FIFA, используется в настоящее время',
		success: 'Успешно',
		finished: 'Завершён',
		payed: 'Оплачен',
		progress: 'В процессе',
	},
	de: {
		created: 'ERSTELLEN',
		accepted: 'ZAHLUNG AKZEPTIERT',
		out_of_stock: 'NICHT AUF LAGER',
		warning: 'Warnung',
		wrong_credentials: 'FALSCHE ZUGANGSDATEN',
		wrong_backup: 'FALSCHE BACKUP',
		no_enough_stock: 'NICHT GENUG Münzen',
		not_enough_stock: 'NICHT GENUG Münzen',
		no_enough_coins_to_start: 'NICHT GENUG Münzen UM ZU BEGINNEN',
		not_enough_coins_to_start: 'NICHT GENUG Münzen UM ZU BEGINNEN',
		waiting_payment: 'ZAHLUNG WIRD ERWARTET',
		payment_failed: 'ZAHLUNG FEHLGESCHLAGEN',
		error_payment: 'ZAHLUNG FEHLGESCHLAGEN',
		no_access_to_fifa_21_webapp: 'Kein Zugang zur WEB-APP FIFA 21',
		error_fut: 'FUT FEHLER',
		fut_error: 'FUT FEHLER',
		customer_online: 'FIFA-Konto wird verwendet',
		success: 'Erfolg',
		finished: 'BEENDET',
		payed: 'BEZAHLT',
		progress: 'WIRD VERARBEITET',
	},
	fr: {
		created: 'CRÉÉE',
		accepted: 'acceptée',
		out_of_stock: 'RUPTURE DE STOCK',
		warning: 'Avertissement',
		wrong_credentials: 'IDENTIFIANTS ERRONÉS',
		wrong_backup: 'CODE DE SAUVEGARDE ERRONÉ',
		no_enough_stock: 'PAS ASSEZ DE Crédits',
		not_enough_stock: 'PAS ASSEZ DE Crédits',
		no_enough_coins_to_start: 'PAS ASSEZ DE Crédits POUR COMMENCER',
		not_enough_coins_to_start: 'PAS ASSEZ DE Crédits POUR COMMENCER',
		waiting_payment: 'EN ATTENTE DE PAIEMENT',
		payment_failed: 'ÉCHEC DU PAIEMENT',
		error_payment: 'ÉCHEC DU PAIEMENT',
		no_access_to_fifa_21_webapp: 'Aucun accès à APPLICATION WEB FIFA 21',
		error_fut: 'ERREUR FUT',
		fut_error: 'ERREUR FUT',
		customer_online: "compte FIFA actuellement en cours d'utilisation",
		success: 'Succès',
		finished: 'TERMINÉ',
		payed: 'PAYÉE',
		progress: 'EN COURS',
	},
	it: {
		created: 'CREAZIONE',
		accepted: 'ACCETTATO',
		out_of_stock: 'ESAURITO',
		warning: 'Avvertimento',
		wrong_credentials: 'CREDENZIALI ERRATE',
		wrong_backup: 'BACKUP ERRATO',
		no_enough_stock: 'crediti INSUFFICIENTI',
		not_enough_stock: 'crediti INSUFFICIENTI',
		no_enough_coins_to_start: 'crediti INSUFFICIENTI',
		not_enough_coins_to_start: 'crediti INSUFFICIENTI',
		waiting_payment: 'IN ATTESA DEL PAGAMENTO',
		payment_failed: 'PAGAMENTO NON RIUSCITO',
		error_payment: 'PAGAMENTO NON RIUSCITO',
		no_access_to_fifa_21_webapp: 'Accesso alla web-app di FIFA 21 non disponibile',
		error_fut: 'ERRORE IN FUT',
		fut_error: 'ERRORE IN FUT',
		customer_online: 'Account FIFA in uso',
		success: 'Success',
		finished: 'OPERAZIONE CONCLUSA',
		payed: 'PAGATO',
		progress: 'IN CORSO',
	},
	ar: {
		created: 'إنشاء',
		accepted: 'مقبول',
		out_of_stock: 'غير متوفر',
		warning: 'تحذير',
		wrong_credentials: 'بيانات اعتماد خاطئة',
		wrong_backup: 'كود احتياطي خاطئ',
		no_enough_stock: 'عملات معدنية غير كافية للبدء',
		not_enough_stock: 'عملات معدنية غير كافية للبدء',
		no_enough_coins_to_start: 'عملات معدنية غير كافية للبدء',
		not_enough_coins_to_start: 'عملات معدنية غير كافية للبدء',
		waiting_payment: 'في انتظار السداد',
		payment_failed: 'فشلت عملية الدفع',
		error_payment: 'فشلت عملية الدفع',
		no_access_to_fifa_21_webapp: 'لا يمكن الوصول إلى تطبيق FIFA 21 على الويب',
		error_fut: 'FUT خطأ',
		fut_error: 'FUT خطأ',
		customer_online: 'حساب FIFA قيد الاستخدام حاليًا',
		success: 'النجاح',
		finished: 'مكتمل',
		payed: 'مدفوع',
		progress: 'قيد التنفيذ',
	},
	nl: {
		created: 'AANGEMAAKT',
		accepted: 'AANVAARD',
		out_of_stock: 'UITVERKOCHT',
		warning: 'Waarschuwing',
		wrong_credentials: 'VERKEERDE GEGEVENS',
		wrong_backup: 'VERKEERDE BACK-UP',
		no_enough_stock: 'NIET GENOEG MUNTEN',
		not_enough_stock: 'NIET GENOEG MUNTEN',
		no_enough_coins_to_start: 'NIET GENOEG MUNTEN OM TE STARTEN',
		not_enough_coins_to_start: 'NIET GENOEG MUNTEN OM TE STARTEN',
		waiting_payment: 'WACHT OP BETALING',
		payment_failed: 'BETALING MISLUKT',
		error_payment: 'BETALING MISLUKT',
		no_access_to_fifa_21_webapp: 'Geen toegang tot FIFA 21 WEB-APP',
		error_fut: 'FOUT FUT',
		fut_error: 'FOUT FUT',
		customer_online: 'FIFA account momenteel in gebruik',
		success: 'Succes',
		finished: 'AFGEWERKT',
		payed: 'BETAALD',
		progress: 'BEZIG MET UITVOERING',
	},
	es: {
		created: 'CREADO',
		accepted: 'ACEPTADO',
		out_of_stock: 'AGOTADAS',
		warning: 'Advertencia',
		wrong_credentials: 'CREDENCIALES INCORRECTAS',
		wrong_backup: 'COPIA DE SEGURIDAD INCORRECTA',
		no_enough_stock: 'MONEDAS INSUFICIENTES PARA INICIAR',
		not_enough_stock: 'MONEDAS INSUFICIENTES PARA INICIAR',
		no_enough_coins_to_start: 'MONEDAS INSUFICIENTES PARA INICIAR',
		not_enough_coins_to_start: 'MONEDAS INSUFICIENTES PARA INICIAR',
		waiting_payment: 'ESPERANDO PAGO',
		payment_failed: 'ERROR DEL PAGO',
		error_payment: 'ERROR DEL PAGO',
		no_access_to_fifa_21_webapp: 'Sin acceso a la aplicación web de «FIFA 21»',
		error_fut: 'ERROR FUT',
		fut_error: 'ERROR FUT',
		customer_online: 'Cuenta de «FIFA» ya en uso',
		success: 'Éxito',
		finished: 'COMPLETADO',
		payed: 'PAGADO',
		progress: 'EN CURSO',
	},
	pt: {
		created: 'CRIAR',
		accepted: 'ACEITE',
		out_of_stock: 'SEM STOCK',
		warning: 'Aviso',
		wrong_credentials: 'CREDENCIAIS ERRADAS',
		wrong_backup: 'CÓDIGO DE SEGURANÇA ERRADO',
		no_enough_stock: 'SEM MOEDAS SUFICIENTES PARA COMEÇAR',
		not_enough_stock: 'SEM MOEDAS SUFICIENTES PARA COMEÇAR',
		no_enough_coins_to_start: 'SEM MOEDAS SUFICIENTES PARA COMEÇAR',
		not_enough_coins_to_start: 'SEM MOEDAS SUFICIENTES PARA COMEÇAR',
		waiting_payment: 'A AGUARDAR PAGAMENTO',
		payment_failed: 'O PAGAMENTO FALHOU',
		error_payment: 'O PAGAMENTO FALHOU',
		no_access_to_fifa_21_webapp: 'Sem acesso à APLICAÇÃO ONLINE FIFA 21',
		error_fut: 'ERRO FUT',
		fut_error: 'ERRO FUT',
		customer_online: 'Conta FIFA a ser utilizada atualmente',
		success: 'Sucesso',
		finished: 'CONCLUÍDO',
		payed: 'PAGO',
		progress: 'A DECORRER',
	},
	ch: {
		created: '创建',
		accepted: '已接受',
		out_of_stock: '缺货',
		warning: '警告',
		wrong_credentials: '凭证错误',
		wrong_backup: '备份错误',
		no_enough_stock: '启动金币不足',
		not_enough_stock: '启动金币不足',
		no_enough_coins_to_start: '启动金币不足',
		not_enough_coins_to_start: '启动金币不足',
		waiting_payment: '等待支付中',
		payment_failed: '支付失败',
		error_payment: '支付失败',
		no_access_to_fifa_21_webapp: '无法访问 FIFA 21 WEB-APP',
		error_fut: 'FUT 错误',
		fut_error: 'FUT 错误',
		customer_online: 'FIFA 帐户当前正在使用中',
		success: '成功',
		finished: '已完成',
		payed: '已支付',
		progress: '进行中',
	},
	tr: {
		created: 'OLUŞTUR',
		accepted: 'KABUL EDİLDİ',
		out_of_stock: 'STOKTA YOK',
		warning: 'Uyarıcı',
		wrong_credentials: 'GİRİŞ BİLGİLERİ HATALI',
		wrong_backup: 'BACKUP HATALI',
		no_enough_stock: 'YETERLİ JETON YOK',
		not_enough_stock: 'YETERLİ JETON YOK',
		no_enough_coins_to_start: 'YETERLİ JETON YOK',
		not_enough_coins_to_start: 'YETERLİ JETON YOK',
		waiting_payment: 'ÖDEME BEKLENİYOR',
		payment_failed: 'ÖDEME BAŞARISIZ',
		error_payment: 'ÖDEME BAŞARISIZ',
		no_access_to_fifa_21_webapp: 'FIFA 21 WEB-APP uygulamasına erişilemiyor',
		error_fut: 'FUT HATASI',
		fut_error: 'FUT HATASI',
		customer_online: 'FIFA hesabı halihazırda kullanılıyor',
		success: 'Başarı',
		finished: 'TAMAMLANDI',
		payed: 'ÖDENDİ',
		progress: 'İŞLENİYOR',
	},
	pl: {
		created: 'TWORZENIE',
		accepted: 'ZAAKCEPTOWANE',
		out_of_stock: 'BRAK W MAGAZYNIE',
		warning: 'Ostrzeżenie',
		wrong_credentials: 'BŁĘDNE DANE',
		wrong_backup: 'BŁĘDNY KOD ZAPASOWY',
		no_enough_stock: 'ZA MAŁO MONET NA START',
		not_enough_stock: 'ZA MAŁO MONET NA START',
		no_enough_coins_to_start: 'ZA MAŁO MONET NA START',
		not_enough_coins_to_start: 'ZA MAŁO MONET NA START',
		waiting_payment: 'OCZEKIWANIE NA PŁATNOŚĆ',
		payment_failed: 'PŁATNOŚĆ NIEUDANA',
		error_payment: 'PŁATNOŚĆ NIEUDANA',
		no_access_to_fifa_21_webapp: 'Brak dostępu do aplikacji WWW FIFA 21',
		error_fut: 'BŁĄD FUT',
		fut_error: 'BŁĄD FUT',
		customer_online: 'Konto FIFA jest obecnie używane',
		success: 'Sukcesy',
		finished: 'ZAKOŃCZONO',
		payed: 'OPŁACONE',
		progress: 'W TRAKCIE REALIZACJI',
	},
	sw: {
		created: 'SKAPA',
		accepted: 'GODKÄND',
		out_of_stock: 'EJ I LAGER',
		warning: 'Varning',
		wrong_credentials: 'FELAKTIGA UPPGIFTER',
		wrong_backup: 'FELAKTIG RESERVKOD',
		no_enough_stock: 'SAKNAS MYNT FÖR ATT STARTA',
		not_enough_stock: 'SAKNAS MYNT FÖR ATT STARTA',
		no_enough_coins_to_start: 'SAKNAS MYNT FÖR ATT STARTA',
		not_enough_coins_to_start: 'SAKNAS MYNT FÖR ATT STARTA',
		waiting_payment: 'VÄNTAR PÅ BETALNING',
		payment_failed: 'BETALNINGSFEL',
		error_payment: 'BETALNINGSFEL',
		no_access_to_fifa_21_webapp: 'Ingen tillgång till FIFA 21:s webbapp',
		error_fut: 'FUT-FEL',
		fut_error: 'FUT-FEL',
		customer_online: 'FIFA-kontot används',
		success: 'Framgång',
		finished: 'LEVERERAD',
		payed: 'BETALAD',
		progress: 'BEHANDLAS',
	},
	no: {
		created: 'OPPRETT',
		accepted: 'GODTATT',
		out_of_stock: 'IKKE FLERE TILGJENGELIG',
		warning: 'Advarsel',
		wrong_credentials: 'FEIL OPPLYSNINGER',
		wrong_backup: 'FEIL RESERVE',
		no_enough_stock: 'IKKE NOK MYNTER TIL Å KUNNE STARTE',
		not_enough_stock: 'IKKE NOK MYNTER TIL Å KUNNE STARTE',
		no_enough_coins_to_start: 'IKKE NOK MYNTER TIL Å KUNNE STARTE',
		not_enough_coins_to_start: 'IKKE NOK MYNTER TIL Å KUNNE STARTE',
		waiting_payment: 'AVVENTER BETALING',
		payment_failed: 'BETALING MISLYKTES',
		error_payment: 'BETALING MISLYKTES',
		no_access_to_fifa_21_webapp: 'Ingen tilgang til FIFA 21-NETTAPPEN',
		error_fut: 'FUT-FEIL',
		fut_error: 'FUT-FEIL',
		customer_online: 'FIFA-kontoen er i bruk',
		success: 'Suksess',
		finished: 'FULLFØRT',
		payed: 'BETALT',
		progress: 'PÅGÅR',
	},
};

export const getTranslate = {
	en: {
		forPaymentError: 'Payment failed',
		profileCodesErrors: 'Please enter backup codes. The code should be at least 8 characters long.',
		loading: 'Loading',
		seePassword: 'See password',
		hidePassword: 'Hide password',
		toDay: 'Today',
		yesterDay: 'Yesterday',
		numDay: '#',
		login: 'Login',
		amount: 'Amount',
		price: 'Price',
		status: 'Status',
		profileFormSuccess: 'Order is changed, the status',
		enterCode: 'Enter code',
		wrongCode: 'Wrong Backup',
		backupCode: 'Backup codes',
		email: 'Email',
		username: 'Username',
		account: 'Account',
		password: 'Password',
		emailOrPassword: 'Email or password is invalid',
		fbError: 'Error Login',
		isInvalid: 'invalid',
		isAlreadyTaken: 'is already taken',
		wrongCredentials: 'Wrong Credentials',
		reportProblem: 'Report a problem',
		cancelOrder: 'Cancel order',
		saveChanges: 'Save changes',
		haveCoupon: 'Have an coupon',
		logOut: 'Log out',
		youLogged: 'You’re successfully logged as',
		coinsFor: 'Coins for',
		orderCreationError: 'Order creation error',
		orderUpdateError: 'Order update error',
		invalidPromo: 'Invalid promo code',
		couponExpired: 'Coupon expired',
		buyingCoins: 'Buying coins on royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'en-US',
		MissingOrInvalidCredentialsCode: 'Connection error, please try again!',
	},
	ru: {
		forPaymentError: 'Платёж не прошел',
		profileCodesErrors: 'Пожалуйста, введите резервные коды. Код должен состоять не менее чем из 8 символов.',
		loading: 'Загрузка',
		seePassword: 'Посмотреть пароль',
		hidePassword: 'Скрыть пароль',
		toDay: 'Сегодня',
		yesterDay: 'Вчера',
		numDay: '#',
		login: 'Логин',
		amount: 'Сумма монет',
		price: 'Стоимость',
		status: 'Статус',
		profileFormSuccess: 'Заказ изменен, статус',
		enterCode: 'Введите код',
		wrongCode: 'Неверный резервный код',
		backupCode: 'Резервные коды',
		email: 'Почта',
		username: 'Логин',
		account: 'Аккаунт',
		password: 'Пароль',
		emailOrPassword: 'Неверная электронная почта или пароль',
		fbError: 'Error Login',
		isInvalid: 'неверно',
		isAlreadyTaken: 'уже занят',
		isAlreadyTaken1: 'уже занята',
		wrongCredentials: 'Неверные учетные данные',
		reportProblem: 'Сообщить о проблеме',
		cancelOrder: 'Отменить заказ',
		saveChanges: 'Сохранить изменения',
		haveCoupon: 'Есть купон',
		logOut: 'Выйти',
		youLogged: 'Вы успешно вошли как',
		coinsFor: 'Монет за',
		orderCreationError: 'Ошибка создания заказа',
		orderUpdateError: 'Ошибка обновления заказа',
		invalidPromo: 'Промокод не найден',
		couponExpired: 'Срок действия купона истек',
		buyingCoins: 'Купить монеты на royalfut.com',
		currency: '₽',
		currencyName: 'RUB',
		paymentsLanguage: 'ru-RU',
		MissingOrInvalidCredentialsCode: 'Ошибка подключения, пожалуйста, попробуйте еще раз!',
	},
	de: {
		forPaymentError: 'Zahlung fehlgeschlagen',
		profileCodesErrors: 'Bitte geben Sie die Backup-Codes ein. Der Code muss mindestens 8 Zeichen lang sein.',
		loading: 'Laden',
		seePassword: 'Siehe Passwort',
		hidePassword: 'Passwort ausblenden',
		toDay: 'Heute',
		yesterDay: 'Eben',
		numDay: 'Nr.',
		login: 'Anmelden',
		amount: 'Anzahl',
		price: 'Preis',
		status: 'Status',
		profileFormSuccess: 'Reihenfolge wird geändert, der status',
		enterCode: 'code eingeben',
		wrongCode: 'FALSCHE BACKUP',
		backupCode: 'Backup-codes',
		email: 'E-mail',
		username: 'Benutzername',
		account: 'Konto',
		password: 'Passwort',
		emailOrPassword: 'E-Mail-Adresse oder Passwort ungültig',
		fbError: 'Error Login',
		isInvalid: 'ungültig',
		isAlreadyTaken: 'ist bereits vergeben',
		wrongCredentials: 'FALSCHE ZUGANGSDATEN',
		reportProblem: 'Ein problem melden',
		cancelOrder: 'Bestellung abbrechen',
		saveChanges: 'ÄNDERUNGEN SPEICHERN',
		haveCoupon: 'Ich habe einen Gutschein',
		logOut: 'AUSLOGGEN',
		youLogged: 'Sie haben sich erfolgreich angemeldet als Benutzer',
		coinsFor: 'Münzen für',
		orderCreationError: 'Fehler bei der Auftragserstellung',
		orderUpdateError: 'Um update-Fehler',
		invalidPromo: 'Promocode ungültig',
		couponExpired: 'Gutschein abgelaufen',
		buyingCoins: 'Münzen kaufen auf royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'de-DE',
		MissingOrInvalidCredentialsCode: 'Verbindungsproblem. Bitte erneut versuchen!',
	},
	fr: {
		forPaymentError: 'ÉCHEC DU PAIEMENT',
		profileCodesErrors: 'Veuillez entrer le code de sauvegarde qui doit comporter au moins 8 caractères.',
		loading: 'Chargement',
		seePassword: 'Voir le mot de passe',
		hidePassword: 'Masquer le mot de passe',
		toDay: "Aujourd'hui",
		yesterDay: 'Hier',
		numDay: '№',
		login: 'Connexion',
		amount: 'Nombre',
		price: 'Prix',
		status: 'Statut',
		profileFormSuccess: "L'ordre est changé, le statut",
		enterCode: 'ENTRER LE CODE',
		wrongCode: 'CODE DE SAUVEGARDE ERRONÉ',
		backupCode: 'Codes de sauvegarde',
		email: 'E-mail',
		username: "Le nom d'utilisateur",
		account: 'Compte',
		password: 'Mot de passe',
		emailOrPassword: 'Adresse électronique ou mot de passe non valide',
		fbError: 'Error Login',
		isInvalid: 'non valide',
		isAlreadyTaken: 'déjà enregistré',
		wrongCredentials: 'IDENTIFIANTS ERRONÉS',
		reportProblem: 'Signaler un problème',
		cancelOrder: 'Annuler la commande',
		saveChanges: 'ENREGISTRER LES MODIFICATIONS',
		haveCoupon: 'Si vous avez un coupon',
		logOut: 'SE DÉCONNECTER',
		youLogged: "Vous êtes connecté avec succès avec votre nom d'utilisateur",
		coinsFor: 'Crédits pour',
		orderCreationError: 'Erreur de création de commande',
		orderUpdateError: 'Erreur de mise à jour de commande',
		invalidPromo: 'Code promotionnel non valide',
		couponExpired: 'Coupon expiré',
		buyingCoins: 'ACHETER DES CRÉDITS sur royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'fr-FR',
		MissingOrInvalidCredentialsCode: 'Erreur de connexion, veuillez réessayer !',
	},
	it: {
		forPaymentError: 'PAGAMENTO NON RIUSCITO',
		profileCodesErrors: 'inserisci i codici di backup. Ogni codice deve contenere almeno 8 caratteri',
		loading: 'Loading',
		seePassword: 'Vedi password',
		hidePassword: 'Nascondi password',
		toDay: 'Oggi',
		yesterDay: 'Ieri',
		numDay: 'Num.',
		login: 'Accedi',
		amount: 'Quantità',
		price: 'Prezzo',
		status: 'Stato',
		profileFormSuccess: "L'ordine è cambiato, lo stato",
		enterCode: 'INSERISCI IL CODICE',
		wrongCode: 'BACKUP ERRATO',
		backupCode: 'Codice di backup',
		email: 'E-mail',
		username: 'Il nome utente',
		account: 'Account',
		password: 'Password',
		emailOrPassword: 'E-mail o password non valida',
		fbError: 'Error Login',
		isInvalid: 'non valida',
		isAlreadyTaken: 'è già in uso',
		wrongCredentials: 'CREDENZIALI ERRATE',
		reportProblem: 'Segnala un problema',
		cancelOrder: 'Annulla ordine',
		saveChanges: 'SALVA LE MODIFICHE',
		haveCoupon: 'Avere un coupon',
		logOut: 'DISCONNETTERSI	',
		youLogged: 'Accesso riuscito con il nome utente',
		coinsFor: 'crediti per',
		orderCreationError: "Errore di creazione dell'ordine",
		orderUpdateError: "Errore di aggiornamento dell'ordine",
		invalidPromo: 'codice promozionale non valido',
		couponExpired: 'coupon scaduto',
		buyingCoins: 'Acquisto di crediti su royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'it-IT',
		MissingOrInvalidCredentialsCode: 'Errore di connessione, riprova!',
	},
	ar: {
		forPaymentError: 'فشلت عملية الدفع',
		profileCodesErrors: 'يُرجى إدخال الأكواد الاحتياطية. يجب أن يكون الكود 8 حروف على الأقل',
		loading: 'تحميل',
		seePassword: 'انظر كلمة المرور',
		hidePassword: 'إخفاء كلمة المرور',
		toDay: 'اليوم',
		yesterDay: 'أمس',
		numDay: '#',
		login: 'تسجيل الدخول',
		amount: 'المقدار',
		price: 'السعر',
		status: 'الحالة',
		profileFormSuccess: 'يتم تغيير النظام ، والحالة',
		enterCode: 'إدخال الكود',
		wrongCode: 'كود احتياطي خاطئ',
		backupCode: 'الأكواد الاحتياطية',
		email: 'البريد الإلكتروني',
		username: 'اسم المستخدم',
		account: 'الحساب',
		password: 'كلمة المرور',
		emailOrPassword: 'البريد الإلكتروني أو كلمة المرور غير صالحين',
		fbError: 'Error Login',
		isInvalid: 'صالحين',
		isAlreadyTaken: 'هذا مستخدم بالفعل',
		wrongCredentials: 'بيانات اعتماد خاطئة',
		reportProblem: 'الإبلاغ عن مشكلة',
		cancelOrder: 'إلغاء الطلب',
		saveChanges: 'حفظ التغييرات',
		haveCoupon: 'لديك قسيمة',
		logOut: 'تسجيل خروج',
		youLogged: 'لقد سجلت الدخول بنجاح باسم',
		coinsFor: 'من العملات مقابل',
		orderCreationError: 'خطأ في إنشاء الطلب',
		orderUpdateError: 'خطأ في تحديث الطلب',
		invalidPromo: 'كود ترويجي غير صالح',
		couponExpired: 'القسيمة منتهية الصلاحية',
		buyingCoins: 'شراء العملات على royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'ar-EG',
	},
	nl: {
		forPaymentError: 'Betaling mislukt',
		profileCodesErrors: 'Gelieve je backup codes in te voeren. De code moet minstens 8 tekens lang zijn.',
		loading: 'Laden',
		seePassword: 'Zie wachtwoord',
		hidePassword: 'Wachtwoord verbergen',
		toDay: 'Vandaag',
		yesterDay: 'Gisteren',
		numDay: '#',
		login: 'Login',
		amount: 'Aantal',
		price: 'Prijs',
		status: 'Status',
		profileFormSuccess: 'Volgorde is veranderd, de status',
		enterCode: 'Code invoeren',
		wrongCode: 'VERKEERDE BACK-UP',
		backupCode: 'Backup-codes',
		email: 'E-mail',
		username: 'Gebruikersnaam',
		account: 'Account',
		password: 'Wachtwoord',
		emailOrPassword: 'Ongeldig e-mailadres of wachtwoord.',
		fbError: 'Error Login',
		isInvalid: 'Ongeldig',
		isAlreadyTaken: 'bestaat al',
		wrongCredentials: 'VERKEERDE GEGEVENS',
		reportProblem: 'Een probleem melden',
		cancelOrder: 'Bestelling annuleren',
		saveChanges: 'Wijzigingen opslaan',
		haveCoupon: 'Ik heb een kortingsbon',
		logOut: 'UITLOGGEN',
		youLogged: 'Je bent met succes aangemeld als',
		coinsFor: 'Munten voor',
		orderCreationError: 'bestelling aanmaken fout',
		orderUpdateError: 'bestelling fout bijwerken',
		invalidPromo: 'Ongeldige kortingscode',
		couponExpired: 'Kortingsbon niet meer geldig',
		buyingCoins: 'Munten kopen op royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'nl-NL',
		MissingOrInvalidCredentialsCode: 'Verbindingsfout, gelieve het nog eens te proberen!',
	},
	es: {
		forPaymentError: 'Error del pago',
		profileCodesErrors: 'Indique el código de copia de seguridad. El código debe tener al menos 8 caracteres.',
		loading: 'Carga',
		seePassword: 'Ver contraseña',
		hidePassword: 'Ocultar contraseña',
		toDay: 'Hoy',
		yesterDay: 'Ayer',
		numDay: 'N.º',
		login: 'Usuario',
		amount: 'Cantidad',
		price: 'Precio',
		status: 'Estado',
		profileFormSuccess: 'El orden se cambia, el estado',
		enterCode: 'INDIQUE EL CÓDIGO',
		wrongCode: 'COPIA DE SEGURIDAD INCORRECTA',
		backupCode: 'Códigos de copia de seguridad',
		email: 'Correo electrónico',
		username: 'Nombre',
		account: 'CUENTA',
		password: 'Contraseña',
		emailOrPassword: 'El correo electrónico o la contraseña no son válidos.',
		fbError: 'Error Login',
		isInvalid: 'no válidos',
		isAlreadyTaken: 'ya está ocupado.',
		wrongCredentials: 'CREDENCIALES INCORRECTAS',
		reportProblem: 'Informar de un problema',
		cancelOrder: 'Cancelar pedido',
		saveChanges: 'GUARDAR CAMBIOS',
		haveCoupon: 'Tengo un cupón',
		logOut: 'SALIR',
		youLogged: 'Se ha registrado correctamente como',
		coinsFor: 'monedas por',
		orderCreationError: 'Error de creación de pedidos',
		orderUpdateError: 'Error de actualización de pedido',
		invalidPromo: 'Código promocional no válido',
		couponExpired: 'Cupón caducado',
		buyingCoins: 'Comprar monedas en royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'es-ES',
		MissingOrInvalidCredentialsCode: 'Error de conexión. Inténtelo de nuevo.',
	},
	pt: {
		forPaymentError: 'O pagamento falhou',
		profileCodesErrors: 'Introduz o código de segurança. O código deve ter, pelo menos, 8 caracteres.',
		loading: 'Carregamento',
		seePassword: 'Ver passe',
		hidePassword: 'Esconder a passe',
		toDay: 'Hoje',
		yesterDay: 'Ontem',
		numDay: 'N.º',
		login: 'Início de sessão',
		amount: 'Montante',
		price: 'Preço',
		status: 'Estado',
		profileFormSuccess: 'A ordem é alterada, o estado',
		enterCode: 'INTRODUZIR O CÓDIGO',
		wrongCode: 'CÓDIGO DE SEGURANÇA ERRADO',
		backupCode: 'Código de segurança',
		email: 'E-mail',
		username: 'Nome de utilizador',
		account: 'CONTA',
		password: 'Palavra-passe',
		emailOrPassword: 'O e-mail ou palavra-passe são inválidos',
		fbError: 'Error Login',
		isInvalid: 'inválidos',
		isAlreadyTaken: 'já foi escolhido',
		wrongCredentials: 'CREDENCIAIS ERRADAS',
		reportProblem: 'Comunicar um problema',
		cancelOrder: 'Cancelar a ordem',
		saveChanges: 'GUARDAR ALTERAÇÕES',
		haveCoupon: 'Tenho um cupão',
		logOut: 'TERMINAR SESSÃO',
		youLogged: 'Iniciaste sessão com sucesso com o nome de',
		coinsFor: 'Moedas por',
		orderCreationError: 'Erro de criação da ordem',
		orderUpdateError: 'Erro de actualização da ordem',
		invalidPromo: 'código promocional inválido',
		couponExpired: 'Cupão caducado',
		buyingCoins: 'Compra de moedas royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'pt-PT',
		MissingOrInvalidCredentialsCode: 'Erro de ligação, tenta novamente!',
	},
	ch: {
		forPaymentError: '支付失败',
		profileCodesErrors: '请输入备份代码。代码长度不应少于 8 个字符',
		loading: '加载',
		seePassword: '查看密码',
		hidePassword: '隐藏密码',
		toDay: '今天',
		yesterDay: '昨天',
		numDay: '#',
		login: '登录',
		amount: '数量',
		price: '价格',
		status: '状态',
		profileFormSuccess: '订单被改变，状态',
		enterCode: '输入代码',
		wrongCode: '备份错误',
		backupCode: '备份代码',
		email: '电子邮件',
		username: '用户名',
		account: '帐户',
		password: '密码',
		emailOrPassword: '电子邮件或密码无效',
		fbError: 'Error Login',
		isInvalid: '无效',
		isAlreadyTaken: '已被占用',
		wrongCredentials: '凭证错误',
		reportProblem: '报告问题',
		cancelOrder: '取消订单',
		saveChanges: '保存更改',
		haveCoupon: '有一张优惠券',
		logOut: '退出',
		youLogged: '您已成功以用户名登录',
		coinsFor: '购买',
		orderCreationError: '订单创建错误',
		orderUpdateError: '订单更新错误',
		invalidPromo: '无效的促销代码',
		couponExpired: '优惠券已过期',
		buyingCoins: '购买硬币 royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'jp-JP',
		MissingOrInvalidCredentialsCode: '连接错误，请再次尝试!',
	},
	tr: {
		forPaymentError: 'Ödeme başarısız',
		profileCodesErrors: 'Lütfen backup kodunu girin. Kod en az 8 karakter uzunluğunda olmalıdır.',
		loading: 'Yükleniyor',
		seePassword: 'Bkz. şifre',
		hidePassword: 'Şifreyi gizle',
		toDay: 'Bugün',
		yesterDay: 'Dün',
		numDay: '#',
		login: 'Giriş',
		amount: 'Miktar',
		price: 'Fiyat',
		status: 'Durum',
		profileFormSuccess: 'Sipariş değişti, durum',
		enterCode: 'Kodu gir',
		wrongCode: 'BACKUP HATALI',
		backupCode: 'Backup kodları',
		email: 'E-POSTA',
		username: 'Kullanıcı adı',
		account: 'hesabı',
		password: 'Şifre',
		emailOrPassword: 'E-posta veya şifre geçersiz.',
		fbError: 'Error Login',
		isInvalid: 'geçersiz',
		isAlreadyTaken: 'adı alınmış.',
		wrongCredentials: 'GİRİŞ BİLGİLERİ HATALI',
		reportProblem: 'Bir sorunu bildir',
		cancelOrder: 'Siparişi iptal et',
		saveChanges: 'Değişiklikleri Kaydet',
		haveCoupon: 'İndirim kuponunuz mu var',
		logOut: 'ÇIKIŞ',
		youLogged: 'Kullanıcı adı olarak başarıyla kaydoldunuz.',
		coinsFor: 'Jeton bedeli',
		orderCreationError: 'Sipariş oluşturma hatası',
		orderUpdateError: 'Sipariş güncelleme hatası',
		invalidPromo: 'İndirim kodu geçersiz',
		couponExpired: 'Kuponun süresi dolmuş',
		buyingCoins: 'Para satın alma royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'tr-TR',
		MissingOrInvalidCredentialsCode: 'Bağlantı hatası. Lütfen tekrar deneyin!',
	},
	pl: {
		forPaymentError: 'PŁATNOŚĆ NIEUDANA',
		profileCodesErrors: 'Wprowadź kody zapasowe. Kod powinien mieć co najmniej 8 znaków',
		loading: 'Ładowanie',
		seePassword: 'Zobacz hasło',
		hidePassword: 'Ukryj hasło',
		toDay: 'Dziś',
		yesterDay: 'Wczoraj',
		numDay: '#',
		login: 'Login',
		amount: 'Liczba',
		price: 'Cena',
		status: 'Stan',
		profileFormSuccess: 'Kolejność została zmieniona, status',
		enterCode: 'WPROWADŹ KOD',
		wrongCode: 'BŁĘDNY KOD ZAPASOWY',
		backupCode: 'Kody zapasowe',
		email: 'E-mail',
		username: 'Nazwa użytkownika',
		account: 'KONTO',
		password: 'Hasło',
		emailOrPassword: 'Błędny e-mail lub hasło',
		fbError: 'Error Login',
		isInvalid: 'hasło',
		isAlreadyTaken: 'jest już zajęta',
		wrongCredentials: 'BŁĘDNE DANE',
		reportProblem: 'Zgłoś problem',
		cancelOrder: 'Anuluj zamówienie',
		saveChanges: 'Zapisz zmiany',
		haveCoupon: 'Jeśli masz kupon',
		logOut: 'WYLOGUJ		',
		youLogged: 'Poprawnie zalogowano nazwą użytkownika',
		coinsFor: 'mnt. za',
		orderCreationError: 'Błąd tworzenia zamówienia',
		orderUpdateError: 'Błąd aktualizacji zamówienia',
		invalidPromo: 'Błędny kod promocyjny',
		couponExpired: 'kupon przeterminowany',
		buyingCoins: 'Skup monet naroyalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'pl-PL',
		MissingOrInvalidCredentialsCode: 'Błąd połączenia, spróbuj jeszcze raz!',
	},
	sw: {
		forPaymentError: 'BETALNINGSFEL',
		profileCodesErrors: 'Ange reservkod. Koden ska vara minst 8 tecken lång.',
		loading: 'Lastning',
		seePassword: 'Se lösenord',
		hidePassword: 'Dölj lösenord',
		toDay: 'Idag',
		yesterDay: 'Igår',
		numDay: '#',
		login: 'Konto',
		amount: 'Antal',
		price: 'Pris',
		status: 'Status',
		profileFormSuccess: 'Order ändras, status',
		enterCode: 'Ange kod',
		wrongCode: 'FELAKTIG RESERVKOD',
		backupCode: 'Reservkoder',
		email: 'E-post',
		username: 'Användarnamn',
		account: 'KONTO',
		password: 'Lösenord',
		emailOrPassword: 'E-post eller lösenord stämmer inte',
		fbError: 'Error Login',
		isInvalid: 'stämmer',
		isAlreadyTaken: 'är redan taget',
		wrongCredentials: 'FELAKTIGA UPPGIFTER',
		reportProblem: 'Rapportera ett problem',
		cancelOrder: 'Avbryt beställning',
		saveChanges: 'Spara ändringar',
		haveCoupon: 'Har en kupong',
		logOut: 'LOGGA UT',
		youLogged: 'Du har loggat in som username',
		coinsFor: 'mynt för',
		orderCreationError: 'Orderskapande fel',
		orderUpdateError: 'Orderuppdateringsfel',
		invalidPromo: 'Ogiltig kampanjkod',
		couponExpired: 'Kupongen har gått ut',
		buyingCoins: 'Köpa mynt på royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'sv-SV',
		MissingOrInvalidCredentialsCode: 'Anslutningsfel. Försök igen.',
	},
	no: {
		forPaymentError: 'Betaling mislyktes',
		profileCodesErrors: 'oppgi reservekode, minst 8 tegn',
		loading: 'Lasting',
		seePassword: 'Se passordet ditt',
		hidePassword: 'Skjul passord',
		toDay: 'I dag',
		yesterDay: 'I går',
		numDay: '#',
		login: 'Logg inn',
		amount: 'Antall',
		price: 'Pris',
		status: 'Status',
		profileFormSuccess: 'Rekkefølgen er endret status',
		enterCode: 'Skriv inn kode',
		wrongCode: 'FEIL RESERVE',
		backupCode: 'Reservekoder',
		email: 'E-postadresse',
		username: 'Brukernavn',
		account: 'Konto',
		password: 'Passord',
		emailOrPassword: 'Ugyldig e-postadresse eller passord',
		fbError: 'Error Login',
		isInvalid: 'Ugyldig',
		isAlreadyTaken: 'er allerede i bruk',
		wrongCredentials: 'FEIL OPPLYSNINGER',
		reportProblem: 'Informar de un problema',
		cancelOrder: 'Cancelar pedido',
		saveChanges: 'LAGRE ENDRINGER',
		haveCoupon: 'Har en kupong',
		logOut: 'LOGG UT',
		youLogged: 'Du har logget deg inn som username',
		coinsFor: 'mynter for',
		orderCreationError: 'Error de creación de pedidos',
		orderUpdateError: 'Error de actualización de pedido',
		invalidPromo: 'Ugyldig kampanjekode',
		couponExpired: 'Kupongen er utløpt',
		buyingCoins: 'Comprar monedas en royalfut.com',
		currency: '€',
		currencyName: 'EUR',
		paymentsLanguage: 'no-NO',
		MissingOrInvalidCredentialsCode: 'Tilkoblingsfeil. Prøv igjen.',
	},
};

export const getTranslateMessage = (locale, message) => {
	const value = {
		en: {
			forPaidError: `Your order ${message ? `№${message} ` : ''}successfully paid. Please tap the banner to continue proceeding your order.`,
			forCredentialsError: `Order ${message} – Invalid account data`,
			forBackupError: `Order ${message} – Invalid backup codes`,
			forCustomerError: `Order ${message} – User is currently online`,
			yourOrder: `Your order <em>№${message}</em> in progress`,
		},
		ru: {
			forPaidError: `Ваш заказ ${message ? `№${message} ` : ''} успешно оплачен. Пожалуйста, нажмите на баннер, чтобы продолжить оформление заказа.`,
			forCredentialsError: `Неверные учётные данные по заказу ${message}`,
			forBackupError: `Неверные резервные коды по заказу ${message}`,
			forCustomerError: `Пользователь находится онлайн по заказу ${message}`,
			yourOrder: `Ваш заказ <em>№${message}</em> в процессе выполнения`,
		},
		de: {
			forPaidError: `Deine Bestellung mit der ${message ? `№${message} ` : ''}wurde erfolgreich bezahlt. Bitte tippe auf das Banner, um mit deiner Bestellung fortzufahren.`,
			forCredentialsError: `Bestell ${message} – Konto-Informationen ungültig`,
			forBackupError: `Bestell ${message} – Backup-Code ungültig`,
			forCustomerError: `Bestell ${message} – Benutzer ist derzeit online`,
			yourOrder: `Ihre Bestellung <em>№${message}</em> FALSCHE ZUGANGSDATEN`,
		},
		fr: {
			forPaidError: `Le paiement de votre commande ${message ? `№${message} ` : ''}a abouti. Veuillez toucher la bannière pour poursuivre le traitement de votre commande.`,
			forCredentialsError: `Commande ${message} - Données sur le compte non valides`,
			forBackupError: `Commande ${message} – Codes de sauvegarde non valides`,
			forCustomerError: `Commande ${message} – Utilisateur actuellement connecté`,
			yourOrder: `Votre commande <em>№${message}</em> EN COURS`,
		},
		it: {
			forPaidError: `Il pagamento del tuo ordine ${message ? `№${message} ` : ''}è stato effettuato. Tocca il banner per procedere con l'ordine.`,
			forCredentialsError: `Ordine ${message} – Dati dell'account non validi`,
			forBackupError: `Ordine ${message} – Codici di backup non validi`,
			forCustomerError: `Ordine ${message} – L'utente è online`,
			yourOrder: `Il Tuo Ordine <em>№${message}</em> in corso`,
		},
		ar: {
			forPaidError: `تم سداد طلبك ${message ? `№${message} ` : ''}بنجاح. الرجاء الضغط على الشعار لمتابعة إجراء طلبك.`,
			forCredentialsError: `طلب رقم ${message} – بيانات حساب غير صالحة`,
			forBackupError: `طلب رقم ${message} – أكواد احتياطية غير صالحة`,
			forCustomerError: `طلب رقم ${message} – المستخدم متصل حاليًا`,
			yourOrder: `تم سداد طلبك <em>№${message}</em> قيد التنفيذ`,
		},
		nl: {
			forPaidError: `Je bestelling ${message ? `№${message} ` : ''}is betaald. Tik op de banner om door te gaan met je bestelling.`,
			forCredentialsError: `Bestelling ${message} – Ongeldige account gegevens`,
			forBackupError: `Bestelling ${message} – Ongeldige backup-codes`,
			forCustomerError: `Bestelling ${message} – gebruiker is momenteel online`,
			yourOrder: `Je bestelling <em>№${message}</em> BEZIG MET UITVOERING`,
		},
		es: {
			forPaidError: `Su pedido ${message ? `№${message} ` : ''} se ha pagado correctamente. Haga clic en el banner para continuar con el proceso..`,
			forCredentialsError: `Pedido ${message} – datos de cuenta no válidos`,
			forBackupError: `Pedido ${message} – códigos de copia de seguridad no válidos`,
			forCustomerError: `Pedido ${message} – el usuario ya está conectado`,
			yourOrder: `Su pedido <em>№${message}</em> EN CURSO`,
		},
		pt: {
			forPaidError: `O teu pedido ${message ? `№${message} ` : ''}foi pago com sucesso. Toca no banner para continuares a processar o teu pedido.`,
			forCredentialsError: `Pedido ${message} – Dados de conta inválidos`,
			forBackupError: `Pedido ${message} – Códigos de segurança inválidos`,
			forCustomerError: `Pedido ${message} – O utilizador está atualmente online`,
			yourOrder: `O teu pedido <em>№${message}</em> A DECORRER`,
		},
		ch: {
			forPaidError: `您的订单 ${message ? `№${message} ` : ''} 已成功支付。请点击横幅继续订购。`,
			forCredentialsError: `订单 ${message} – 无效的帐户数据`,
			forBackupError: `订单 ${message} – 无效的备份代码`,
			forCustomerError: `订单 ${message} – 用户当前在线`,
			yourOrder: `您的订单 <em>№${message}</em> 进行中`,
		},
		tr: {
			forPaidError: `Numaralı siparişinizin ${message ? `№${message} ` : ''} ödemesi başarıyla yapıldı. Lütfen siparişi tamamlamak için banda tıklayın..`,
			forCredentialsError: `Sipariş ${message} – Hesap bilgileri geçersiz`,
			forBackupError: `Sipariş ${message} – Geçersiz backup kodu`,
			forCustomerError: `Sipariş ${message} – Kullanıcı şu anda çevrimiçi`,
			yourOrder: `Numaralı siparişinizin <em>№${message}</em> İŞLENİYOR`,
		},
		pl: {
			forPaidError: `Twoje zamówienie ${message ? `nr${message} ` : ''}zostało poprawnie opłacone. Dotknij bannera, aby kontynuować przetwarzanie zamówienia.`,
			forCredentialsError: `Zamówienie ${message} – błędne dane konta`,
			forBackupError: `Zamówienie ${message} – błędne kody zapasowe`,
			forCustomerError: `Zamówienie ${message} – użytkownik jest obecnie online`,
			yourOrder: `Twoje zamówienie <em>№${message}</em> W TRAKCIE REALIZACJI`,
		},
		sw: {
			forPaidError: `Beställning ${message ? `№${message} ` : ''}har betalats. Tryck på bannern för att fortsätta.`,
			forCredentialsError: `Beställning ${message} – ogiltiga kontouppgifter`,
			forBackupError: `Beställning ${message} – ogiltiga reservkoder`,
			forCustomerError: `Beställning ${message} – användaren är online`,
			yourOrder: `Beställning <em>№${message}</em> BEHANDLAS`,
		},
		no: {
			forPaidError: `Betaling for bestilling ${message ? `nr.${message} ` : ''}er gjennomført. Trykk på banneret for å fortsette med bestillingen.`,
			forCredentialsError: `Bestilling ${message} – ugyldige kontoopplysninger`,
			forBackupError: `Bestilling ${message} – ugyldige reservekoder`,
			forCustomerError: `Bestilling ${message} – brukeren er på nett`,
			yourOrder: `Betaling for bestilling <em>№${message}</em> PÅGÅR`,
		},
	};

	return value[locale];
};

/*
 * Default error messages
*/
export const validMessage = {
	en: {
		required: 'This field is required.',
		remote: 'Please fix this field.',
		email: 'Please enter a valid email address.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Please enter at least {0} characters.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'Wrong backup codes',
		// Error message when connection is down
		generic: 'Connection error, please try again!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Error occured, please try again!',
	},
	ru: {
		required: 'Это поле является обязательным.',
		remote: 'Пожалуйста, исправьте это поле.',
		email: 'Пожалуйста, введите действительный адрес электронной почты.',
		url: 'Пожалуйста, введите действительный URL-адрес.',
		date: 'Пожалуйста, введите действительную дату.',
		dateISO: 'Пожалуйста, введите действительную дату (ISO).',
		number: 'Пожалуйста, введите действительный номер.',
		digits: 'Пожалуйста, введите только цифры.',
		equalTo: 'Пожалуйста, введите то же самое значение еще раз.',
		maxlength: $.validator.format('Пожалуйста, введите не более {0} символов.'),
		minlength: $.validator.format('Пожалуйста, введите не менее {0} символов.'),
		rangelength: $.validator.format('Пожалуйста, введите значение длиной от {0} до {1} символов.'),
		range: $.validator.format('Пожалуйста, введите значение между {0} и {1}.'),
		max: $.validator.format('Пожалуйста, введите значение меньше или равно {0}.'),
		min: $.validator.format('Пожалуйста, введите значение, большее или равное {0}.'),
		step: $.validator.format('Пожалуйста, введите кратное {0}.'),
		codes: 'Неверные резервные коды',
		// Error message when connection is down
		generic: 'Ошибка подключения, пожалуйста, попробуйте еще раз!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Произошла ошибка, пожалуйста, попробуйте еще раз!',
	},
	de: {
		required: 'Das ist ein Pflichtfeld.',
		remote: 'Bitte beheben Sie dieses Feld.',
		email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
		url: 'Bitte geben Sie eine gültige URL.',
		date: 'Bitte geben Sie ein gültiges Datum ein.',
		dateISO: 'Bitte geben Sie ein gültiges Datum (ISO).',
		number: 'Bitte geben Sie eine gültige Nummer ein.',
		digits: 'Bitte geben Sie nur Ziffern ein.',
		equalTo: 'Bitte geben Sie den gleichen Wert erneut ein.',
		maxlength: $.validator.format('Bitte geben Sie nicht mehr als {0} Zeichen.'),
		minlength: $.validator.format('Bitte geben Sie mindestens {0} Zeichen ein.'),
		rangelength: $.validator.format('Bitte geben Sie einen Wert zwischen {0} und {1} Zeichen lang sein.'),
		range: $.validator.format('Bitte geben Sie einen Wert zwischen {0} und {1}.'),
		max: $.validator.format('Bitte geben Sie einen Wert kleiner oder gleich {0}.'),
		min: $.validator.format('Bitte geben Sie einen Wert größer oder gleich {0}.'),
		step: $.validator.format('Bitte geben Sie ein Vielfaches von {0} ein.'),
		codes: 'Falsche backup-codes',
		// Error message when connection is down
		generic: 'Verbindungsproblem. Bitte erneut versuchen!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Ein Fehler ist aufgetreten. Bitte erneut versuchen!',
	},
	fr: {
		required: 'Ce champ est obligatoire.',
		remote: 'Veuillez corriger ce champ.',
		email: 'Veuillez entrer une adresse électronique valide.',
		url: "S'il vous plaît entrer une URL valide.",
		date: 'Veuillez entrer une Date valide.',
		dateISO: "S'il vous plaît entrer une date valide (ISO).",
		number: 'Veuillez saisir un numéro valide.',
		digits: 'Veuillez saisir uniquement des Chiffres.',
		equalTo: 'Veuillez saisir à nouveau la même valeur.',
		maxlength: $.validator.format("S'il vous plaît ne pas entrer plus de {0} caractères."),
		minlength: $.validator.format('Veuillez entrer au moins {0} caractères.'),
		rangelength: $.validator.format("S'il vous plaît entrer une valeur entre {0} et {1} caractères longs."),
		range: $.validator.format("S'il vous plaît entrer une valeur entre {0} et {1}."),
		max: $.validator.format("S'il vous plaît entrer une valeur inférieure ou égale à {0}."),
		min: $.validator.format("S'il vous plaît entrer une valeur supérieure ou égale à {0}."),
		step: $.validator.format('Veuillez saisir un multiple de {0}.'),
		codes: 'Codes de sauvegarde incorrects',
		// Error message when connection is down
		generic: 'Erreur de connexion, veuillez réessayer !',
		// Error message when server responds with >= 400 error code
		genericCode: "Une erreur s'est produite, veuillez réessayer !",
	},
	it: {
		required: 'Questo campo è obbligatorio.',
		remote: 'Si prega di risolvere questo campo.',
		email: 'Inserisci un indirizzo e-mail valido.',
		url: 'Inserisci un URL valido.',
		date: 'Si prega di inserire una data valida.',
		dateISO: 'Inserire una data valida (ISO).',
		number: 'Si prega di inserire un numero valido.',
		digits: 'Si prega di inserire solo cifre.',
		equalTo: 'Inserire nuovamente lo stesso valore.',
		maxlength: $.validator.format('Inserire non più di {0} caratteri.'),
		minlength: $.validator.format('Inserisci almeno {0} caratteri.'),
		rangelength: $.validator.format('Inserire un valore compreso tra {0} E {1}.'),
		range: $.validator.format('Inserire un valore compreso tra {0} E {1}.'),
		max: $.validator.format('Inserire un valore minore o uguale a {0}.'),
		min: $.validator.format('Inserire un valore maggiore o uguale a {0}.'),
		step: $.validator.format('Inserire un multiplo di {0}.'),
		codes: 'Codici di backup errati',
		// Error message when connection is down
		generic: 'Errore di connessione, riprova!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Si è verificato un errore, riprova!',
	},
	ar: {
		required: 'هذه الخانة مطلوبة.',
		remote: 'Please fix this field.',
		email: 'يُرجى إدخال عنوان بريد إلكتروني صالح.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('يُرجى إدخال {0} حروف على الأقل.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'رموز احتياطية خاطئة',
		// Error message when connection is down
		generic: 'خطأ في الاتصال، يُرجى المحاولة مجددًا!',
		// Error message when server responds with >= 400 error code
		genericCode: 'حدث خطأ، يُرجى المحاولة مجددًا!',
	},
	nl: {
		required: 'Dit veld is verplicht.',
		remote: 'Please fix this field.',
		email: 'Gelieve een geldig e-mailadres in te voeren',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Gelieve minstens {0} tekens in te voeren.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'VERKEERDE BACK-UP CODES',
		// Error message when connection is down
		generic: 'Verbindingsfout, gelieve het nog eens te proberen!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Er is een fout opgetreden, gelieve het nog eens te proberen!',
	},
	es: {
		required: 'Campo obligatorio.',
		remote: 'Please fix this field.',
		email: 'Indique una dirección de correo electrónico válida.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Indique al menos {0} caracteres.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'COPIA DE SEGURIDAD INCORRECTA',
		// Error message when connection is down
		generic: 'Error de conexión. Inténtelo de nuevo.',
		// Error message when server responds with >= 400 error code
		genericCode: 'Se ha producido un error. Inténtelo de nuevo.',
	},
	pt: {
		required: 'Este campo é obrigatório.',
		remote: 'Please fix this field.',
		email: 'Introduz um endereço de e-mail válido.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Introduz, pelo menos, {0} caracteres.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'Códigos de salvaguarda errados',
		// Error message when connection is down
		generic: 'Erro de ligação, tenta novamente!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Ocorreu um erro, tenta novamente!',
	},
	ch: {
		required: '必填字段。',
		remote: 'Please fix this field.',
		email: '请输入有效的电子邮件地址。',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('请输入至少 {0} 个字符。'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: '错误的备份代码',
		// Error message when connection is down
		generic: '连接错误，请再次尝试！',
		// Error message when server responds with >= 400 error code
		genericCode: '发生错误，请重新尝试！',
	},
	tr: {
		required: 'Zorunlu alan',
		remote: 'Please fix this field.',
		email: 'Lütfen geçerli bir e-posta adresi girin.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Lütfen en az {0} karakter girin.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'Backup HATALI kodları',
		// Error message when connection is down
		generic: 'Bağlantı hatası. Lütfen tekrar deneyin.',
		// Error message when server responds with >= 400 error code
		genericCode: 'Bir hata oldu. Lütfen tekrar deneyin.',
	},
	pl: {
		required: 'To pole jest wymagane.',
		remote: 'Please fix this field.',
		email: 'Podaj poprawny adres e-mail.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Wprowadź co najmniej {0} znaków.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'BŁĘDNY KOD ZAPASOWY kod',
		// Error message when connection is down
		generic: 'Błąd połączenia, spróbuj jeszcze raz!',
		// Error message when server responds with >= 400 error code
		genericCode: 'Wystąpił błąd, spróbuj jeszcze raz!',
	},
	sw: {
		required: 'Obligatoriskt fält.',
		remote: 'Please fix this field.',
		email: 'Ange en giltig e-postadress.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Ange minst {0} tecken.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'FELAKTIG Reservkoder',
		// Error message when connection is down
		generic: 'Anslutningsfel. Försök igen.',
		// Error message when server responds with >= 400 error code
		genericCode: 'Ett fel inträffade. Försök igen.',
	},
	no: {
		required: 'Dette feltet er påkrevd.',
		remote: 'Please fix this field.',
		email: 'Skriv inn en gyldig e-postadresse.',
		url: 'Please enter a valid URL.',
		date: 'Please enter a valid date.',
		dateISO: 'Please enter a valid date (ISO).',
		number: 'Please enter a valid number.',
		digits: 'Please enter only digits.',
		equalTo: 'Please enter the same value again.',
		maxlength: $.validator.format('Please enter no more than {0} characters.'),
		minlength: $.validator.format('Skriv inn minst {0} tegn.'),
		rangelength: $.validator.format('Please enter a value between {0} and {1} characters long.'),
		range: $.validator.format('Please enter a value between {0} and {1}.'),
		max: $.validator.format('Please enter a value less than or equal to {0}.'),
		min: $.validator.format('Please enter a value greater than or equal to {0}.'),
		step: $.validator.format('Please enter a multiple of {0}.'),
		codes: 'FEIL Reservekoder',
		// Error message when connection is down
		generic: 'Tilkoblingsfeil. Prøv igjen.',
		// Error message when server responds with >= 400 error code
		genericCode: 'Det har oppstått en feil. Prøv igjen.',
	},
};
